//  cheb_check.c -- bit-exactness check for the new range-reduced
//  transcendentals (src/posit/pgmp.h + ptrans.h) against a large corpus of
//  (width, function, input, expected-output) vectors.
//
//  The vectors are generated by tools/gen_cheb_vectors.py, which calls
//  libmath/tools/unum_cheb_check.py's mpmath-verified reference functions
//  (exp_ref/log_g/log2_g/log10_g/sin_g/cos_g/tan_g/atan_g/asin_g/acos_g) --
//  the SAME algorithm-of-record the Hoon /lib/unum rewrite was checked
//  against.  This harness links libsoftunum directly (no ctypes) and diffs
//  every line, so it exercises the real C ABI end to end.
//
//  Usage:  cheb_check <vectors-file>

#include <softunum.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef uint32_t (*fn1_t)(uint32_t);

static uint32_t call1(int n, const char *op, uint32_t x) {
  if ( n == 8 ) {
    if ( !strcmp(op, "exp") )   return p8_exp(x);
    if ( !strcmp(op, "log") )   return p8_log(x);
    if ( !strcmp(op, "log2") )  return p8_log2(x);
    if ( !strcmp(op, "log10") ) return p8_log10(x);
    if ( !strcmp(op, "sin") )   return p8_sin(x);
    if ( !strcmp(op, "cos") )   return p8_cos(x);
    if ( !strcmp(op, "tan") )   return p8_tan(x);
    if ( !strcmp(op, "atan") )  return p8_atan(x);
    if ( !strcmp(op, "asin") )  return p8_asin(x);
    if ( !strcmp(op, "acos") )  return p8_acos(x);
  } else if ( n == 16 ) {
    if ( !strcmp(op, "exp") )   return p16_exp(x);
    if ( !strcmp(op, "log") )   return p16_log(x);
    if ( !strcmp(op, "log2") )  return p16_log2(x);
    if ( !strcmp(op, "log10") ) return p16_log10(x);
    if ( !strcmp(op, "sin") )   return p16_sin(x);
    if ( !strcmp(op, "cos") )   return p16_cos(x);
    if ( !strcmp(op, "tan") )   return p16_tan(x);
    if ( !strcmp(op, "atan") )  return p16_atan(x);
    if ( !strcmp(op, "asin") )  return p16_asin(x);
    if ( !strcmp(op, "acos") )  return p16_acos(x);
  } else if ( n == 32 ) {
    if ( !strcmp(op, "exp") )   return p32_exp(x);
    if ( !strcmp(op, "log") )   return p32_log(x);
    if ( !strcmp(op, "log2") )  return p32_log2(x);
    if ( !strcmp(op, "log10") ) return p32_log10(x);
    if ( !strcmp(op, "sin") )   return p32_sin(x);
    if ( !strcmp(op, "cos") )   return p32_cos(x);
    if ( !strcmp(op, "tan") )   return p32_tan(x);
    if ( !strcmp(op, "atan") )  return p32_atan(x);
    if ( !strcmp(op, "asin") )  return p32_asin(x);
    if ( !strcmp(op, "acos") )  return p32_acos(x);
  }
  fprintf(stderr, "unknown (n=%d, op=%s)\n", n, op);
  exit(2);
}

typedef struct { int n; char op[8]; long pass, fail; int shown; } tally_t;

static tally_t *find_tally(tally_t *tallies, int *count, int n, const char *op) {
  for ( int i = 0; i < *count; i++ )
    if ( tallies[i].n == n && !strcmp(tallies[i].op, op) ) return &tallies[i];
  tally_t *t = &tallies[(*count)++];
  t->n = n; strncpy(t->op, op, sizeof(t->op) - 1); t->op[sizeof(t->op) - 1] = 0;
  t->pass = t->fail = 0; t->shown = 0;
  return t;
}

int main(int argc, char **argv) {
  const char *path = (argc > 1) ? argv[1] : "tools/cheb_vectors.txt";
  FILE *f = fopen(path, "r");
  if ( !f ) { fprintf(stderr, "cannot open %s\n", path); return 2; }

  tally_t tallies[64];
  int ntallies = 0;
  long total = 0, total_fail = 0;
  char line[256];
  while ( fgets(line, sizeof(line), f) ) {
    int n; char op[8]; unsigned long long in, exp;
    if ( sscanf(line, "%d %7s 0x%llx 0x%llx", &n, op, &in, &exp) != 4 ) continue;
    total++;
    uint32_t got = call1(n, op, (uint32_t)in);
    tally_t *t = find_tally(tallies, &ntallies, n, op);
    if ( (unsigned long long)got == exp ) {
      t->pass++;
    } else {
      t->fail++; total_fail++;
      if ( t->shown < 5 ) {
        printf("FAIL p%d_%s(0x%llx) = 0x%x, want 0x%llx\n", n, op, in, got, exp);
        t->shown++;
      }
    }
  }
  fclose(f);

  printf("\n%-6s %-6s %10s %10s\n", "width", "fn", "pass", "fail");
  for ( int i = 0; i < ntallies; i++ )
    printf("%-6d %-6s %10ld %10ld\n", tallies[i].n, tallies[i].op, tallies[i].pass, tallies[i].fail);
  printf("\nTOTAL: %ld cases, %ld failures\n", total, total_fail);
  return total_fail ? 1 : 0;
}
